# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Vezgammont
    url: https://vezgammont.it
  - name: Gitlab
    url: https://gitlab.vezgammont.it
  - name: Taiga
    url: https://taiga.vezgammont.it
  - name: Mattermost
    url: https://mattermost.vezgammont.it
  - name: Jenkins
    url: https://jenkins.vezgammont.it
  - name: Sonarqube
    url: https://sonarqube.vezgammont.it

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  #baseUrl: /
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** of the [vezgammont](https://vezgammont.it) services"
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/samuelemusiani/status.vezgammont.it).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
